# Generated by Django 5.2.8 on 2025-11-05 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoen_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opinion',
            old_name='texto',
            new_name='mensaje',
        ),
        migrations.RenameField(
            model_name='opinion',
            old_name='autor',
            new_name='nombre',
        ),
    ]
